const productos_a_mover = [
    {id: '1', nombre: 'PECHUGA RELLENA', imagen: 'https://i.ibb.co/tY5BBVm/10.jpg', cantidad: 0, precio: 70, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '2', nombre: 'BISTEC ASADO', imagen: 'https://i.ibb.co/TBnNC4s/bistec-asado.jpg', cantidad: 0, precio: 70, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '3', nombre: 'PECHUGA ASADA', imagen: 'https://i.ibb.co/rcQw4Kj/pechuga-asada.jpg', cantidad: 0, precio: 70, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '4', nombre: 'DESAYUNO TARDE CLUB SANWICH', imagen: 'https://i.ibb.co/BG1bq0m/24.jpg', cantidad: 0, precio: 50, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '5', nombre: 'DESAYUNO HUEVO A LA MEXICANA', imagen: 'https://i.ibb.co/Y0rSjrt/4-huevo-a-la-mexicana.jpg', cantidad: 0, precio: 40, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '6', nombre: 'DESAYUNO HUEVO RANCHERO', imagen: 'https://i.ibb.co/rFzmPGh/5-huevo-ranchero.jpg', cantidad: 0, precio: 35, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '7', nombre: 'DESAYUNO HUEVO MOTULEÑO', imagen: 'https://i.ibb.co/Z8zrsyV/6-huevo-motule-o.jpg', cantidad: 0, precio: 50, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '8', nombre: 'DESAYUNO HUEVO ESTRELLADO', imagen: 'https://i.ibb.co/sR2MCp8/7-huevos-estrellados.jpg', cantidad: 0, precio: 30, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '9', nombre: 'DESAYUNO OMELET', imagen: 'https://i.ibb.co/wJG7Rp2/8-omelet.jpg', cantidad: 0, precio: 40, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '10', nombre: 'DESAYUNO HUEVO DIVORCIADOS', imagen: 'https://i.ibb.co/VBC1fLd/9-huevos-divorciados.jpg', cantidad: 0, precio: 50, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '11', nombre: 'TARDE PECHUGA EMPANIZADA', imagen: 'https://i.ibb.co/61x0s7d/10-p3chuga-empanizada.jpg', cantidad: 0, precio: 50, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '12', nombre: 'DESAYUNO CHILAQUILES', imagen: 'https://i.ibb.co/NsKLcgb/11-chilaquiles.jpg', cantidad: 0, precio: 50, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '13', nombre: 'DESAYUNO ENCHILADAS SUISAS', imagen: 'https://i.ibb.co/1Zrjpdw/9.jpg', cantidad: 0, precio: 50, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '14', nombre: 'DESAYUNO ENMOLADAS', imagen: 'https://i.ibb.co/QPrX4bD/12-enmoladas.jpg', cantidad: 0, precio: 50, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '15', nombre: 'DESAYUNO TACOS DORADOS', imagen: 'https://i.ibb.co/dj1wQT2/13-tacos-dorados.jpg', cantidad: 0, precio: 40, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '16', nombre: 'DESAYUNO HOTCAKES', imagen: 'https://i.ibb.co/VjGTqQ9/15-hotkakes.jpg', cantidad: 0, precio: 40, extra: "", total: 0, provedor: 'prov_2' },
    {id: '17', nombre: 'DESAYUNO SINCRONISADAS', imagen: 'https://i.ibb.co/f9rWzg4/15-sincronisadas.jpg', cantidad: 0, precio: 40, extra: "", total: 0, provedor: 'prov_2' },
    {id: '18', nombre: 'DESAYUNO MOLLETES', imagen: 'https://i.ibb.co/MGnB1dP/19.jpg', cantidad: 0, precio: 50, extra: "", total: 0, provedor: 'prov_2' },
    {id: '19', nombre: 'TARDE TORTA BISTEK', imagen: 'https://i.ibb.co/D9LsLFj/16-torta-de-bistec.jpg', cantidad: 0, precio: 35, extra: "", total: 0, provedor: 'prov_2' },
    {id: '20', nombre: 'DESAYUNO COCTEL DE FRUTAS', imagen: 'https://i.ibb.co/yBZXYng/13.jpg', cantidad: 0, precio: 50, extra: "", total: 0, provedor: 'prov_2' },
    {id: '21', nombre: 'DESAYUNO CAFE', imagen: 'https://i.ibb.co/ZBhmptQ/17-cafe.jpg', cantidad: 0, precio: 10, extra: "", total: 0, provedor: 'prov_2' },
    {id: '22', nombre: 'DESAYUNO CAFE CON LECHE', imagen: 'https://i.ibb.co/LCTR0sW/18-cafe-con-leche.jpg', cantidad: 0, precio: 20, extra: "", total: 0, provedor: 'prov_2' },
    {id: '23', nombre: 'DESAYUNO JUGO DE NARANJA', imagen: 'https://i.ibb.co/cbd6w41/19-jugo-de-naranja.jpg', cantidad: 0, precio: 28, extra: "", total: 0, provedor: 'prov_2' },
    {id: '24', nombre: 'TACO CARNITAS', imagen: 'https://i.ibb.co/KNqxKcV/tacos-de-carnitas.png', cantidad: 0, precio: 25, extra: "", total: 0, provedor: 'prov_2' },
    {id: '25', nombre: 'REFRESCO', imagen: 'https://i.ibb.co/bscpYzG/refrescos.png', cantidad: 0, precio: 20, extra: "", total: 0, provedor: 'prov_2' },  

];
