using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using clase_QU1R30N.sin_internet.sin_formularios.herramientas;

namespace clase_QU1R30N
{

    internal class iniciar_archivos
    {

        string[] G_caracter_separacion = var_fun_GG.GG_caracter_separacion;
        string[] G_caracter_separacion_funciones_espesificas = var_fun_GG.GG_caracter_separacion_funciones_espesificas;
        string[] G_caracter_para_confirmacion_o_error = var_fun_GG.GG_caracter_para_confirmacion_o_error;

        var_fun_GG vf_GG = new var_fun_GG();

        int G_donde_inicia_la_tabla = var_fun_GG.GG_indice_donde_comensar;

        Tex_base bas = new Tex_base();
        public void iniciar()
        {
            string direccion_archivo_de_direcciones_de_bd = "ARCHIVOS_INICIALES\\INICIO.TXT";
            string fila_inicial = "DIRECCION_DE_LAS_BASES_DE_DATOS" + bas.G_separador_para_funciones_espesificas_[0] + "FILA_INICIAL" + bas.G_separador_para_funciones_espesificas_[0] + "ARREGLO_DE_FILAS_SEPARADO_POR_§//POSDATA_SOLO_IR_AGREGANDO_ARCHIVOS_ASTA_ABAJO_POR_QUE_LAS_FILAS_YA_SON_OCUPADAS_POR_EL_PROGRAMA_Y_NO_BORRAR";
            
            string[] agregar_filas =
            {
                // empiesa desde el 1 por que el 0 es de los archivos iniciales
                /*1*/ "CONFIG\\INF\\INVENTARIO\\INVENTARIO.TXT~0_ID|1_PRODUCTO|2_CONTENIDO|3_TIPO_MEDIDA|4_PRECIO_VENTA|5_COD_BARRAS|6_CANTIDAD|7_COSTO_COMP|8_PROVEDOR¬COSTO_COMP|9_GRUPO|10_NO_PONER_NADA|11_CANT_PRODUC_X_PAQUET|12_TIPO_DE_PRODUCTO|13_LIGAR_PRODUC_SAB|14_IMPUESTOS|15_SI_ES_ELABORADO_QUE_MATERIA_PRIMA_USA_Y_CANTIDAD|16_CADUCIDAD|17_ULTIMO_MOVIMIENTO|18_SUCURSAL_VENT¬COST_VENT|19_CLASIFICACION_PRODUCTO|~1|PRODUCTO|200|ML|100|COD_BAR|1|100|PROVEDOR¬0|PRODUCTO_PIEZA||10|LACTEOS|1|IVA||20240606|20240605|SUC_0¬0|BEBIDA_ALCOLICA|",
                /*2*/ "CONFIG\\INF\\DAT\\PROVEDORES.TXT~0_ID_EMPRESA|1_NOMBRE_EMPRESA|2_NOMBRE_ENCARGADO|3_DIRECCIÓN_EMPRESA|4_CIUDAD_EMPRESA|5_ESTADO_EMPRESA|6_CÓDIGO_POSTAL|7_PAÍS|8_CORREO_ELECTRÓNICO|9_TELÉFONO_ENCARGADO|10_TELEFONO_EMPRESA|11_TIPO_DE_PROVEEDOR|12_PRODUCTOS_SERVICIOS_SUMINISTRADOS|13_CUENTA_BANCO|14_UBICACIÓN_(GPS)|15_NOTAS|16_RECORDATORIO|17_ACTIVO_O_NO_ACTIVO|~",
                /*3*/ "CONFIG\\INF\\DAT\\APRENDICES_E.TXT~0_ID|1_NOMBRE|2_APELLIDO_PATERNO|3_APELLIDO_MATERNO|4_FECHA_DE_NACIMIENTO|5_GÉNERO|6_DIRECCIÓN|7_CIUDAD|8_ESTADO_PROVINCIA|9_CÓDIGO_POSTAL|10_PAÍS|11_CORREO_ELECTRÓNICO|12_TELÉFONO|13_FECHA_DE_INGRESO|14_SUELDO|15_CARGO|16_ESTADO_DE_CURS_APRENDIS_E|17_SUPERVISOR|18_NOTAS|19_AFILIADO|20_FECHA_DE_TERMINACIÓN|21_MOTIVO_DE_TERMINACIÓN|22_HORAS_TRABAJADAS|23_EVALUACIONES_DE_DESEMPEÑO|24_HABILIDADES_Y_CERTIFICACIONES|25_IDIOMAS|26_FECHA_DE_ÚLTIMA_PROMOCIÓN|27_ID_DEL_DEPARTAMENTO_DE_SUPERVISIÓN|28_HISTORIAL_DE_CAPACITACIÓN|29_ÚLTIMO_AUMENTO_DE_SALARIO|30_TIPO_EMPLEADO|31_RANGO_CALIF|~",
                /*4*/ "CONFIG\\AFILIADOS\\AFILIADOS_SIMPLE.TXT~0_ID_USUARIO|1_ID_PAT_COMP|2_TABLA_PAT_COMP|3_ID_ENC_SIMP|4_TABLA_ENC_SIMP|5_PUNTOS_D|6_PUNTOS_D_A_DAR|7_DATOS|8_NIVELES|9_ID_HORIZONTAL|10_TIPO_AFILIADO|~0|0|TABLA_COMPLEJA|0|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|0|0||§1|0|TABLA_COMPLEJA|0|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|1|0||§2|1|TABLA_COMPLEJA|1|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|2|0||§3|2|TABLA_COMPLEJA|2|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|3|0||§4|3|TABLA_COMPLEJA|3|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|4|0||",
                /*5*/ "CONFIG\\AFILIADOS\\AFILIADOS_COMPLEJO.TXT~0_ID_USUARIO|1_ID_PAT_COMP|2_TABLA_PAT_COMP|3_ID_ENC_SIMP|4_TABLA_ENC_SIMP|5_PUNTOS_D|6_PUNTOS_D_A_DAR|7_DATOS|8_NIVELES|9_ID_HORIZONTAL|10_TIPO_AFILIADO|~0|0|TABLA_COMPLEJA|0|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|0|0||§1|0|TABLA_COMPLEJA|0|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|1|0||§2|0|TABLA_COMPLEJA|1|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|2|0||§3|0|TABLA_COMPLEJA|2|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|3|0||§4|0|TABLA_COMPLEJA|3|TABLA_SIMPLE|0|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|4|0||",
                /*6*/ "CONFIG\\AFILIADOS\\NIVELES_E_ID_HORISONTAL_AFILIADOS_SIMPLE.TXT~NIVEL|ID_HORIZONTAL|VACIOS~1|1|§2|1|§3|1|§4|1|",
                /*7*/ "CONFIG\\AFILIADOS\\NIVELES_E_ID_HORISONTAL_AFILIADOS_COMPLEJO.TXT~NIVEL|ID_HORIZONTAL|VACIOS~1|1|§2|1|§3|1|§4|1|",
                /*8*/ "CONFIG\\AFILIADOS\\AFILIADOS_UNIFICADO.TXT~0)ID_USUARIO|1)0IDP╦1IDP¬0PROYECTO_P°0IDP╦1IDP¬1PROYECTO_P|2)0IPUNTOS_D_R¬0PROYECTO_R°1PUNTOS_D_R¬1PROYECTO_R|3)PUNTOS_D_R_TOTALES|4)DATOS|5)NIVEL|6)ID_HORIZONTAL|7)TIPO_AFILIADO|~0|0╦0¬0AFILIADOS_UNIFICADO°0╦0¬AFILIADOS_UNIFICADO1|0¬AFILIADOS_UNIFICADO°0¬AFILIADOS_UNIFICADO1|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|0|0||§1|0¬AFILIADOS_UNIFICADO_P|0¬AFILIADOS_UNIFICADO|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|1|0||§2|1¬AFILIADOS_UNIFICADO|0¬AFILIADOS_UNIFICADO|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|2|0||§3|2¬AFILIADOS_UNIFICADO|0¬AFILIADOS_UNIFICADO|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|3|0||§4|3¬AFILIADOS_UNIFICADO|0¬AFILIADOS_UNIFICADO|0|0_NOM_PRU°1_AP_PAT_PRU°2_APE_MAT_PRU°0╦BANCO°4_CURP°5_CLAV_ELECTOR°6_OTRA_ID_IDENTIFICACION°7_0000000000°8_DIRECCION°9_COLONIA°10_MUNICIOPIO°11_ESTADO°12_CORREO@CORREO.COM|4|0||",
                /*9*/ "CONFIG\\AFILIADOS\\NIVELES_E_ID_HORISONTAL_AFILIADOS_UNIFICADO.TXT~NIVEL|ID_HORIZONTAL|VACIOS~1|1|§2|1|§3|1|§4|1|",
                /*10*/ "CONFIG\\INF\\DAT\\SUCUR.TXT~0_NOM_ID_SUCUR|1_NOMBRE_SUCUR|2_NOMBRE_ENCARGADO|3_DIRECCIÓN_SUCUR|4_CIUDAD_SUCUR|5_ESTADO_SUCUR|6_CÓDIGO_POSTAL|7_PAÍS|8_CORREO_ELECTRÓNICO|9_TELÉFONO_ENCARGADO|10_TELEFONO_SUCUR|11_TIPO_DE_SUCUR|12_PRODUCTOS_SERVICIOS_SUMINISTRADOS|13_CUENTA_BANCO|14_UBICACIÓN_(GPS)|15_NOTAS|16_RECORDATORIO|17_ACTIVO_O_NO_ACTIVO|~",
                

            };

            

            bas.Crear_archivo_y_directorio_opcion_leer_y_agrega_arreglo(direccion_archivo_de_direcciones_de_bd, fila_inicial, agregar_filas, caracter_separacion_fun_esp_objeto: G_caracter_separacion_funciones_espesificas[2]);
            //Tex_base.GG_dir_bd_y_valor_inicial_bidimencional = op_arreglos.agregar_registro_del_array_bidimensional(Tex_base.GG_dir_bd_y_valor_inicial_bidimencional, direccion_archivo_de_direcciones_de_bd, new string[] { bas.G_separador_para_funciones_espesificas });

            for (int i = G_donde_inicia_la_tabla; i < Tex_base.GG_base_arreglo_de_arreglos[0].Length; i++)
            {
                string[] espliteados_direcciones_bases_datos_y_fila_inicial = Tex_base.GG_base_arreglo_de_arreglos[0][i].Split(bas.G_separador_para_funciones_espesificas_[0][0]);
                string[] filas_iniciales = espliteados_direcciones_bases_datos_y_fila_inicial[2].Split(G_caracter_separacion_funciones_espesificas[1][0]);
                if (i > 0)
                {
                    bas.Crear_archivo_y_directorio_opcion_leer_y_agrega_arreglo(espliteados_direcciones_bases_datos_y_fila_inicial[0], espliteados_direcciones_bases_datos_y_fila_inicial[1], filas_iniciales);
                }



            }
        }
    }
}